// general common constants moved here

COMMON.emptyObject = {};
COMMON.BORDER = 300;
COMMON.GRID_WIDTH = 40;
COMMON.GRID_HEIGHT = COMMON.GRID_WIDTH * 0.686 | 0;
COMMON.WALL_ANGLES = 16;
COMMON.WALL_ANGLE_STEP = Math.PI * 2 / COMMON.WALL_ANGLES;
COMMON.STRUCTURE_PER_WOOD = 3;
COMMON.MAX_INTERACT_RADIUS = 100;
COMMON.BARBARIAN_TEAM = 6;
COMMON.MEADOW_COLOR = 0x639141;
COMMON.DRY_MEADOW_COLOR = 0x7e7a5c;
COMMON.GROUND_COLOR = 0x595652;
COMMON.LIGHT_COLOR = 0x808080;
COMMON.PALETTE = "palette.png";
COMMON.INSERT_ARROW = [1, 16, 7, 4];
COMMON.TEAM_COLOR = [{
    mid: 0x8f563b,
    name: 0xc97339
}, {
    mid: 0xff5256,
    name: 0xff5256
}, {
    mid: 0x639bff,
    name: 0x639bff
}, {
    mid: 0x99e550,
    name: 0x99e550
}, {
    mid: 0xfbf236,
    name: 0xfbf236
}, {
    mid: 0xcbdbfc,
    name: 0xcbdbfc
}, {
    mid: 0xeec39a,
    name: 0xeec39a
}];
COMMON.POINT = 1;
COMMON.CIRCLE = 2;
COMMON.RECT = 4;
COMMON.MAX_LEVEL = 9;
COMMON.MAX_POPULATION = 6;
COMMON.TRIBE_RADIUS = 40;
COMMON.SHARE_INTERVAL = 1 / 10;
COMMON.LATENCY = 0.05;
COMMON.TWEEN_DURATION = COMMON.SHARE_INTERVAL * 1.5;
COMMON.REMOVE_DEFAULT = 1;
COMMON.REMOVE_INSTANT = 2;
COMMON.CLEAR_ORDER_INTERVAL = 5.0;
COMMON.MOBILE_CURSOR_OFFSET = -32;
COMMON.FLAG_GUN = 1;
COMMON.FLAG_TURBO = 2;
COMMON.FLAG_MOVING = 4;
COMMON.FLAG_LEFT = 1;
COMMON.FLAG_UP = 2;
COMMON.FLAG_RIGHT = 4;
COMMON.FLAG_DOWN = 8;
COMMON.ANIMAL_PALETTE = 18;
COMMON.TWIST_DURATION = 1.0;
COMMON.distanceDurationFormula = function(distance) {
    return 0.1 + distance * 0.003;
}
COMMON.VOCATIONS = {};
